#!/usr/bin/env bash
# Setup pip conf file
# This file must be populated with extra-index-url with token
if [ ! -d "~/.config/pip" ]; then
    mkdir ~/.config/pip
fi
touch ~/.config/pip/pip.conf

# Setup npm rc file that needs to be populated with registry url and token
touch ~/.npmrc

echo "Fill .config/pip/pip.conf and .npmrc with registry urls and tokens"
