#!/usr/bin/env bash
# Call this in a new git repo to add default files to be excluded

EXCLUDE_PATH=$(git rev-parse --git-common-dir)/info/exclude

# Direnv configuration
echo "shell.nix" >> $EXCLUDE_PATH
echo ".envrc" >> $EXCLUDE_PATH

# Virtualenvs (python)
echo ".venv/*" >> $EXCLUDE_PATH

# Vim buffers
echo "*.swp" >> $EXCLUDE_PATH
echo "*.swo" >> $EXCLUDE_PATH

# Ctags generated tags
echo "tags" >> $EXCLUDE_PATH
echo "tags.safe" >> $EXCLUDE_PATH

# Aider related excludes
echo ".aider*" >> $EXCLUDE_PATH

# Jujutsu
echo ".jj/" >> $EXCLUDE_PATH
